apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    app: app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  project_id: {{ .Values.project_id | b64enc | quote }}
  private_key_id: {{ .Values.private_key_id | b64enc | quote }}
  private_key: {{ .Values.private_key | b64enc | quote }}